# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'webstr.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(251, 160)
        Dialog.setStyleSheet("background-color: rgb(176, 96, 255);")
        self.startwebserverbutton = QtWidgets.QPushButton(Dialog)
        self.startwebserverbutton.setGeometry(QtCore.QRect(10, 40, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        self.startwebserverbutton.setFont(font)
        self.startwebserverbutton.setStyleSheet("background-color: rgb(255, 130, 5);\n"
"border-radius: 10px;\n"
"color: rgb(87, 0, 0);")
        self.startwebserverbutton.setObjectName("startwebserverbutton")
        self.stopwebserverbutton = QtWidgets.QPushButton(Dialog)
        self.stopwebserverbutton.setGeometry(QtCore.QRect(10, 100, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        self.stopwebserverbutton.setFont(font)
        self.stopwebserverbutton.setStyleSheet("background-color: rgb(255, 130, 5);\n"
"border-radius: 10px;\n"
"color: rgb(87, 0, 0);")
        self.stopwebserverbutton.setObjectName("stopwebserverbutton")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(40, 10, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(87, 0, 0);")
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(110, 10, 113, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: rgb(255, 130, 5);\n"
"border-radius: 8px;\n"
"color: rgb(87, 0, 0);")
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "WebStream"))
        self.startwebserverbutton.setText(_translate("Dialog", "Запустить стрим"))
        self.stopwebserverbutton.setText(_translate("Dialog", "Остановить и выйти"))
        self.label.setText(_translate("Dialog", "Порт:"))
        self.lineEdit.setPlaceholderText(_translate("Dialog", "8765"))
